// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace bioskop.Migrations
{
    [DbContext(typeof(BioskopContext))]
    [Migration("20211226170742_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("trajanje")
                        .HasColumnType("int");

                    b.Property<string>("zanr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Filmovi");
                });

            modelBuilder.Entity("Models.Karta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("brSedistaId")
                        .HasColumnType("int");

                    b.Property<int?>("projekcijeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("brSedistaId");

                    b.HasIndex("projekcijeId");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Povlascen")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Models.Projekcija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("RepertoarId")
                        .HasColumnType("int");

                    b.Property<int?>("filmId")
                        .HasColumnType("int");

                    b.Property<int?>("salaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("vreme")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RepertoarId");

                    b.HasIndex("filmId");

                    b.HasIndex("salaId");

                    b.ToTable("Projkecije");
                });

            modelBuilder.Entity("Models.Repertoar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Repertoari");
                });

            modelBuilder.Entity("Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrRedova")
                        .HasColumnType("int");

                    b.Property<int>("BrSedistaPoRedu")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Models.Sediste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrReda")
                        .HasColumnType("int");

                    b.Property<int>("BrSedistaURedu")
                        .HasColumnType("int");

                    b.Property<bool>("Zauzet")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sedista");
                });

            modelBuilder.Entity("Models.Karta", b =>
                {
                    b.HasOne("Models.Sediste", "brSedista")
                        .WithMany()
                        .HasForeignKey("brSedistaId");

                    b.HasOne("Models.Projekcija", "projekcije")
                        .WithMany()
                        .HasForeignKey("projekcijeId");

                    b.Navigation("brSedista");

                    b.Navigation("projekcije");
                });

            modelBuilder.Entity("Models.Projekcija", b =>
                {
                    b.HasOne("Models.Repertoar", null)
                        .WithMany("projekcije")
                        .HasForeignKey("RepertoarId");

                    b.HasOne("Models.Film", "film")
                        .WithMany()
                        .HasForeignKey("filmId");

                    b.HasOne("Models.Sala", "sala")
                        .WithMany()
                        .HasForeignKey("salaId");

                    b.Navigation("film");

                    b.Navigation("sala");
                });

            modelBuilder.Entity("Models.Repertoar", b =>
                {
                    b.Navigation("projekcije");
                });
#pragma warning restore 612, 618
        }
    }
}
